### ISSUE TITLE
Backups for learning circles not working

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/marvin#17]
```
tar: upload/20200610_130141.jpg: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
[2020-09-29 01:00:42,780: ERROR/Worker-1] Backup failed
Traceback (most recent call last):
  File "/opt/app/backup/tasks.py", line 11, in make_backup
    backup_media()
  File "/opt/app/backup/utils.py", line 35, in backup_media
    raise BackupFailed('could not create media backup')
backup.utils.BackupFailed: could not create media backup
```

**Comment by dirkcuys** [comment]
Caused by https://github.com/p2pu/learning-circles/issues/680
