### ISSUE TITLE
Netwell container not working

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/marvin#29]
> Traceback (most recent call last):
>   File "/usr/local/bin/netwell", line 5, in <module>
>     from netwell.command import handle
>   File "/usr/local/lib/python3.12/site-packages/netwell/command.py", line 4, in <module>
>     from netwell import checkers
>   File "/usr/local/lib/python3.12/site-packages/netwell/checkers.py", line 11, in <module>
>     import requests
>   File "/usr/local/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
>     import urllib3
>   File "/usr/local/lib/python3.12/site-packages/urllib3/__init__.py", line 7, in <module>
>     from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
>   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
>     from .exceptions import (
>   File "/usr/local/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
>     from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
> ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by dirkcuys** [comment]
Most likely reason is that the base image for the Docker container got upgraded. In the [Dockerfile](https://github.com/p2pu/marvin/blob/master/roles/monitor/files/p2pu-netwell/Dockerfile) it is specified as `python:3`.

**Comment by dirkcuys** [comment]
updated requirements.txt to solve the issue
